my_posts = [
    {"id": 1, "title": "My first post", "content": "This is exciting!"},
    {"id": 2, "title": "Favorite foods", "content": "I like pizza and sushi."},
    {"id": 3, "title": "Travel plans", "content": "Going to Japan next year."},
    {"id": 4, "title": "Python Programming", "content": "Learning FastAPI is fun."},
    {"id": 5, "title": "Weekend Vibes", "content": "Relaxing and watching movies."},
    {"id": 6, "title": "Workout Routine", "content": "Leg day today!"},
    {"id": 7, "title": "Book Review", "content": "Just finished a great sci-fi novel."},
    {"id": 8, "title": "Tech News", "content": "AI is evolving rapidly."},
    {"id": 9, "title": "Music Recommendations", "content": "Listening to some jazz."},
    {"id": 10, "title": "Cooking Adventures", "content": "Tried making lasagna from scratch."},
    {"id": 11, "title": "Morning Coffee", "content": "Nothing beats a good espresso."},
    {"id": 12, "title": "Pet Antics", "content": "My cat is being crazy again."},
    {"id": 13, "title": "Gardening Tips", "content": "Tomatoes are growing well."},
    {"id": 14, "title": "Photography", "content": "Took some nice landscape shots."},
    {"id": 15, "title": "Gaming", "content": "Playing the new RPG release."},
    {"id": 16, "title": "Coding Challenges", "content": "Solved a tough LeetCode problem."},
    {"id": 17, "title": "Home Decor", "content": "Rearranging the living room."},
    {"id": 18, "title": "Fitness Goals", "content": "Hit a new personal best on bench press."},
    {"id": 19, "title": "Movie Night", "content": "Rewatching Lord of the Rings."},
    {"id": 20, "title": "Study Notes", "content": "Reviewing data structures."},
    {"id": 21, "title": "Nature Walk", "content": "Enjoyed the fresh air in the park."},
    {"id": 22, "title": "Art Project", "content": "Working on a new watercolor painting."},
    {"id": 23, "title": "Daily Reflection", "content": "Grateful for a productive day."}
]